In [129]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import  LinearRegression
from sklearn.model_selection import  train_test_split
from sklearn.metrics import r2_score

In [130]:
df=pd.read_csv("health_fitness_dataset.csv")
df

,exercise_minutes,steps,food_calories,sleep_hours,water_intake_liters,weight
0,42.9,7469.0,2172.0,8.3,3.39,81.12
1,75.9,--,1898.0,6.2,3.66,78.62
2,49.2,unknown,2063.0,9.2,2.92,77.21
3,64.9,4229.0,2443.0,5.6,2.29,89.47
4,42.7,9535.0,1815.0,6.6,1.48,80.41
...,...,...,...,...,...,...
495,59.4,7002.0,2063.0,5.6,2.39,81.93
496,39.0,4807.0,1147.0,8.6,2.43,74.57
497,NaN,9077.0,2231.0,6.6,2.86,82.24
498,59.0,4441.0,1952.0,7.1,2.20,82.37
499,75.8,7566.0,2453.0,7.6,1.86,82.76

In [131]:
df.duplicated().sum()

np.int64(0)

In [132]:
df.isnull().sum()

exercise_minutes       15
steps                   1
food_calories           2
sleep_hours             2
water_intake_liters     0
weight                 10
dtype: int64

In [133]:
# convert all columns to numeric
df = df.apply(pd.to_numeric, errors="coerce")

# remove negative exercise minutes
df = df[df["exercise_minutes"] >= 0]

# fill missing values
df["exercise_minutes"] = df["exercise_minutes"].fillna(df["exercise_minutes"].mean())

# Quartiles
Q1 = df["exercise_minutes"].quantile(0.25)
Q3 = df["exercise_minutes"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# find outliers
outlier = df[(df["exercise_minutes"] < lower) |(df["exercise_minutes"] > upper)]
print(outlier)

     exercise_minutes   steps  food_calories  sleep_hours  \
57               88.1  8008.0         2924.0          7.9
84                5.8  7113.0         1990.0          5.2
180               0.2  8867.0         2047.0          6.3
429               4.0  8371.0         2172.0          8.2

     water_intake_liters  weight
57                  2.07   87.01
84                  2.63   84.08
180                 2.64   83.91
429                 3.29   79.95

In [134]:
print(df.dtypes)

exercise_minutes       float64
steps                  float64
food_calories          float64
sleep_hours            float64
water_intake_liters    float64
weight                 float64
dtype: object

In [135]:
# remove negative exercise minutes
df = df[df["steps"] >= 0]

# fill missing values
df["steps"] = df["steps"].fillna(df["steps"].mean())

# Quartiles
Q1 = df["steps"].quantile(0.25)
Q3 = df["steps"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# find outliers
outlier = df[(df["steps"] < lower) |(df["steps"] > upper)]
print(outlier)

     exercise_minutes    steps  food_calories  sleep_hours  \
104              66.1  13853.0         2556.0          4.6
116              55.2  14305.0         1030.0          6.3
314              46.0  14546.0         1502.0          4.6
345              61.9  15535.0         2052.0          8.4
385              60.3    564.0         1950.0         10.1
457              38.7  15339.0         1721.0          6.0

     water_intake_liters  weight
104                 3.40   83.08
116                 2.20   68.32
314                 2.30   68.32
345                 2.45   76.24
385                 1.34   80.37
457                 3.14   71.40

In [136]:
# remove negative exercise minutes
df = df[df["food_calories"] >= 0]

# fill missing values
df["food_calories"] = df["food_calories"].fillna(df["food_calories"].mean())

# Quartiles
Q1 = df["food_calories"].quantile(0.25)
Q3 = df["food_calories"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# find outliers
outlier = df[(df["food_calories"] < lower) |(df["food_calories"] > upper)]
print(outlier)

     exercise_minutes    steps  food_calories  sleep_hours  \
29               58.9   9543.0         8000.0          7.9
106              68.1   6810.0          839.0          7.8
200              65.5   6523.0         8000.0          6.5
336              58.1   7877.0         3242.0          7.0
412              67.1  10738.0         8000.0          8.5
419              37.8   7168.0         9500.0          7.4

     water_intake_liters  weight
29                  2.78   85.07
106                 3.35   64.19
200                 2.42   89.85
336                 2.00   95.05
412                 1.17   82.53
419                 2.85   82.42

In [137]:
# remove negative exercise minutes
df = df[df["sleep_hours"] >= 0]

# fill missing values
df["sleep_hours"] = df["sleep_hours"].fillna(df["sleep_hours"].mean())

# Quartiles
Q1 = df["sleep_hours"].quantile(0.25)
Q3 = df["sleep_hours"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# find outliers
outlier = df[(df["sleep_hours"] < lower) |(df["sleep_hours"] > upper)]
print(outlier)

     exercise_minutes   steps  food_calories  sleep_hours  \
187              28.5  6631.0         2226.0          3.7
279              62.5  6652.0         1957.0         10.3
378              30.0  7371.0         1295.0          3.2

     water_intake_liters  weight
187                 1.68   89.04
279                 2.76   80.78
378                 1.46   80.66

In [138]:
# remove negative exercise minutes
df = df[df["water_intake_liters"] >= 0]

# fill missing values
df["water_intake_liters"] = df["water_intake_liters"].fillna(df["water_intake_liters"].mean())

# Quartiles
Q1 = df["water_intake_liters"].quantile(0.25)
Q3 = df["water_intake_liters"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# find outliers
outlier = df[(df["water_intake_liters"] < lower) |(df["water_intake_liters"] > upper)]
print(outlier)

     exercise_minutes   steps  food_calories  sleep_hours  \
76               55.6  8906.0         1698.0          8.3
259              43.6  6251.0         1993.0          7.3
420              41.6  7209.0         1666.0          9.2
451              32.3  9242.0         1890.0          5.8

     water_intake_liters  weight
76                  0.82   80.02
259                 0.82   84.23
420                 4.56   77.72
451                 4.51   78.60

In [139]:
# remove negative exercise minutes
df = df[df["weight"] >= 0]

# fill missing values
df["weight"] = df["weight"].fillna(df["weight"].mean())

# Quartiles
Q1 = df["weight"].quantile(0.25)
Q3 = df["weight"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# find outliers
outlier = df[(df["weight"] < lower) |(df["weight"] > upper)]
print(outlier)

     exercise_minutes    steps  food_calories  sleep_hours  \
106              68.1   6810.0          839.0          7.8
111              52.2   6993.0         2740.0          7.0
116              55.2  14305.0         1030.0          6.3
183              59.8   8737.0         1920.0          6.6
277              63.9  11217.0         2388.0          7.7
288              17.6   8788.0         2674.0          7.0
314              46.0  14546.0         1502.0          4.6
336              58.1   7877.0         3242.0          7.0
349              49.9   7016.0         3120.0          5.9
485              61.4  12351.0         1436.0          7.4

     water_intake_liters  weight
106                 3.35   64.19
111                 3.01  200.00
116                 2.20   68.32
183                 1.71  200.00
277                 2.86  300.00
288                 1.61  250.00
314                 2.30   68.32
336                 2.00   95.05
349                 3.14   95.64
485                 2.24   67.42

In [140]:
df

,exercise_minutes,steps,food_calories,sleep_hours,water_intake_liters,weight
0,42.9,7469.0,2172.0,8.3,3.39,81.12
3,64.9,4229.0,2443.0,5.6,2.29,89.47
4,42.7,9535.0,1815.0,6.6,1.48,80.41
5,44.0,5857.0,1677.0,4.7,3.01,81.46
6,56.3,6770.0,2875.0,4.0,2.62,94.16
...,...,...,...,...,...,...
494,69.7,8863.0,2350.0,5.6,3.36,81.19
495,59.4,7002.0,2063.0,5.6,2.39,81.93
496,39.0,4807.0,1147.0,8.6,2.43,74.57
498,59.0,4441.0,1952.0,7.1,2.20,82.37
499,75.8,7566.0,2453.0,7.6,1.86,82.76

In [141]:
df.describe()
df = df[df['weight'] <= 100]
df.describe()

,exercise_minutes,steps,food_calories,sleep_hours,water_intake_liters,weight
count,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000
mean,45.748869,8108.031674,2080.509050,6.938009,2.512285,81.486561
std,14.551724,2046.881886,731.066702,1.214800,0.598723,4.993387
min,0.200000,564.000000,839.000000,3.200000,0.820000,64.190000
25%,36.300000,6733.250000,1742.250000,6.200000,2.100000,78.265000
50%,45.150000,8120.000000,2032.500000,7.000000,2.490000,81.785000
75%,56.000000,9514.750000,2328.500000,7.800000,2.937500,84.695000
max,88.100000,15535.000000,9500.000000,10.300000,4.560000,95.640000

In [142]:
df.shape
df.describe()
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
Index: 442 entries, 0 to 499
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   exercise_minutes     442 non-null    float64
 1   steps                442 non-null    float64
 2   food_calories        442 non-null    float64
 3   sleep_hours          442 non-null    float64
 4   water_intake_liters  442 non-null    float64
 5   weight               442 non-null    float64
dtypes: float64(6)
memory usage: 24.2 KB

exercise_minutes       0
steps                  0
food_calories          0
sleep_hours            0
water_intake_liters    0
weight                 0
dtype: int64

In [143]:
x=df[["exercise_minutes","steps","food_calories","sleep_hours","water_intake_liters"]]
y=df["weight"]

print(x.head())
print(y.head())

   exercise_minutes   steps  food_calories  sleep_hours  water_intake_liters
0              42.9  7469.0         2172.0          8.3                 3.39
3              64.9  4229.0         2443.0          5.6                 2.29
4              42.7  9535.0         1815.0          6.6                 1.48
5              44.0  5857.0         1677.0          4.7                 3.01
6              56.3  6770.0         2875.0          4.0                 2.62
0    81.12
3    89.47
4    80.41
5    81.46
6    94.16
Name: weight, dtype: float64

In [144]:
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
)

In [145]:
model=LinearRegression()

In [146]:
model.fit(x_train,y_train)

LinearRegression()

In [147]:
new_data = [[45, 8000, 2200, 7, 2.5]]
prediction = model.predict(new_data)
print(prediction[0])

81.92476657297188

c:\Users\dhruv\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [148]:
v=model.predict(x_test)
score=r2_score(y_test,v)
print(score)

0.29973307766231705