In [135]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [136]:
df = pd.read_csv('health_fitness_dataset.csv')
df
df.shape
df.head()
df.columns  
df['exercise_minutes'].value_counts(dropna=False)
# NaN 15
df['exercise_minutes'].isnull().sum()
df['exercise_minutes'] = df['exercise_minutes'].fillna(df['exercise_minutes'].mean())
df['exercise_minutes'].isnull().sum()
#filter 
df[df['exercise_minutes'] < 0]
#dropping
df = df[df['exercise_minutes'] >= 0]
df['exercise_minutes'].isnull().sum()
df['exercise_minutes'].describe()
#IQR detection
Q1 = df['exercise_minutes'].quantile(0.25)
Q3 = df['exercise_minutes'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 *IQR
upper = Q3 + 1.5 * IQR
outlier = df[(df['exercise_minutes']< lower) | (df['exercise_minutes'] > upper)]
outlier

,exercise_minutes,steps,food_calories,sleep_hours,water_intake_liters,weight
57,88.1,8008.0,2924.0,7.9,2.07,87.01
84,5.8,7113.0,1990.0,5.2,2.63,84.08
180,0.2,8867.0,2047.0,6.3,2.64,83.91
276,84.5,9248.0,1454.0,5.6,2.44,74.15
369,8.6,8833.0,1915.0,6.0,2.23,85.66
429,4.0,8371.0,2172.0,8.2,3.29,79.95

In [ ]:
df['steps'].dtypes
df['steps'].value_counts(dropna=False)
#convert column to numeric
df['steps'] = pd.to_numeric(df['steps'],errors = 'coerce')
df['steps'].head()
#string to number unkown convert into NaN
df['steps'].isnull().sum()
df['steps'].describe()
df['steps'].median() #8142.0
df['steps'].mean()
#fill NaN value how to know which is best
# use mean when mean kind of = median
# use median when mean far from median
df['steps'] = df['steps'].fillna(df['steps'].mean())
df['steps'].isnull().sum()
#outlier detection
Q1 = df['steps'].quantile(0.25)
Q3 = df['steps'].quantile(0.75)
IQR = Q3 - Q1
# IQR 2769 means 50% of data lies withing this range
lower = Q1 - 1.5 *IQR
upper = Q3 + 1.5 * IQR
outlier = df[(df['steps'] < lower) | (df['steps'] > upper)]
outlier

,exercise_minutes,steps,food_calories,sleep_hours,water_intake_liters,weight
100,66.1,13853.0,2556.0,4.6,3.40,83.08
110,55.2,14305.0,1030.0,6.3,2.20,68.32
298,46.0,14546.0,1502.0,4.6,2.30,68.32
327,61.9,15535.0,2052.0,8.4,2.45,76.24
366,60.3,564.0,1950.0,10.1,1.34,80.37
433,38.7,15339.0,1721.0,6.0,3.14,71.40

In [149]:
df['food_calories'].head()
df['food_calories'].dtype # str 
df['food_calories'] = pd.to_numeric(df['food_calories'],errors = 'coerce')
#error =  'coerce' means if conversion fails convert that value into NaN instrad of giving error
df['food_calories'].dtype
df['food_calories'].isnull().sum()
#df[df['food_calories'].isnull()]
df['food_calories'].mean()
df['food_calories'].median()
df['food_calories'] = df['food_calories'].fillna(df['food_calories'].mean())
df['food_calories'].isnull().sum()
Q1 = df['food_calories'].quantile(0.25)
Q3 = df['food_calories'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 *IQR
upper = Q3 + 1.5 * IQR
outlier = df[(df['food_calories'] < lower) | (df['food_calories'] > upper)]
outlier
# 1500 - 3000 normal 
# 8000 - 10000 unrealistic

#remove
df = df[(df['food_calories'] >= lower) & (df['food_calories'] <= upper)]
outlier.shape
df = df[(df['food_calories'] >= lower) & (df['food_calories'] <= upper)]

In [139]:
df['sleep_hours'].head()
df['sleep_hours'].dtype
df['sleep_hours'].value_counts(dropna=False)
df['sleep_hours'] = pd.to_numeric(df['sleep_hours'], errors='coerce')
df['sleep_hours'].isnull().sum()
df[(df['sleep_hours'].isnull())]
df['sleep_hours'].describe()
df['sleep_hours'].mean()
df['sleep_hours'].median()
df[(df['sleep_hours'].isnull())]
df['sleep_hours'] = df['sleep_hours'].fillna(df['sleep_hours'].median())
df['sleep_hours'].isnull().sum()

Q1 = df['sleep_hours'].quantile(0.25)
Q3 = df['sleep_hours'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 *IQR
upper = Q3 + 1.5 * IQR
outlier = df[(df['sleep_hours'] < lower) | (df['sleep_hours'] > upper)]
outlier

,exercise_minutes,steps,food_calories,sleep_hours,water_intake_liters,weight
187,28.5,6631.0,2226.0,3.7,1.68,89.04
279,62.5,6652.0,1957.0,10.3,2.76,80.78
378,30.0,7371.0,1295.0,3.2,1.46,80.66

In [140]:
df['water_intake_liters'].dtype
df['water_intake_liters'].isnull().sum()
Q1 = df['water_intake_liters'].quantile(0.25)
Q3 = df['water_intake_liters'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 *IQR
upper = Q3 + 1.5 * IQR
outlier = df[(df['water_intake_liters'] < lower) | (df['water_intake_liters'] > upper)]
outlier
df = df[df['water_intake_liters'] >= 0]
df['water_intake_liters']

0      3.39
1      3.66
2      2.92
3      2.29
4      1.48
       ...
495    2.39
496    2.43
497    2.86
498    2.20
499    1.86
Name: water_intake_liters, Length: 479, dtype: float64

In [141]:
df['weight'].isnull().sum()
df[(df['weight'].isnull())]
df['weight'].describe()
df['weight'].mean()
df['weight'].median()
df['weight'] =df['weight'].fillna(df['weight'].mean())
df

,exercise_minutes,steps,food_calories,sleep_hours,water_intake_liters,weight
0,42.900000,7469.00000,2172.0,8.3,3.39,81.12
1,75.900000,8116.86037,1898.0,6.2,3.66,78.62
2,49.200000,8116.86037,2063.0,9.2,2.92,77.21
3,64.900000,4229.00000,2443.0,5.6,2.29,89.47
4,42.700000,9535.00000,1815.0,6.6,1.48,80.41
...,...,...,...,...,...,...
495,59.400000,7002.00000,2063.0,5.6,2.39,81.93
496,39.000000,4807.00000,1147.0,8.6,2.43,74.57
497,45.091959,9077.00000,2231.0,6.6,2.86,82.24
498,59.000000,4441.00000,1952.0,7.1,2.20,82.37
499,75.800000,7566.00000,2453.0,7.6,1.86,82.76

In [142]:
df.describe()
#suspicious value 
df[df['weight'] > 100]
df = df[df['weight'] <= 100]
df.describe()
df.to_csv("cleaned_fitness_data.csv", index=False)

In [143]:
df = pd.read_csv('cleaned_fitness_data.csv')
df.shape
df.describe()
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 475 entries, 0 to 474
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   exercise_minutes     475 non-null    float64
 1   steps                475 non-null    float64
 2   food_calories        475 non-null    float64
 3   sleep_hours          475 non-null    float64
 4   water_intake_liters  475 non-null    float64
 5   weight               475 non-null    float64
dtypes: float64(6)
memory usage: 22.4 KB

exercise_minutes       0
steps                  0
food_calories          0
sleep_hours            0
water_intake_liters    0
weight                 0
dtype: int64

In [144]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score 
#import matplotlib.pyplot as plt
import pickle
df = pd.read_csv('cleaned_fitness_data.csv')
df.columns
X = df[['exercise_minutes','steps','food_calories','sleep_hours','water_intake_liters']]
y = df['weight']
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
model = LinearRegression()
model.fit(x_train,y_train)
new_data = [[45, 8000, 2200, 7, 2.5]]

prediction = model.predict(new_data)
print(prediction[0])

y_pred = model.predict(x_test)
r2 = r2_score(y_test,y_pred)
print("R2 score",r2)

83.21204478389947
R2 score 0.7316742348475487

c:\Users\dhruv\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(