In [212]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,classification_report,mean_absolute_error
import requests
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler

In [213]:

API_KEY = "RXRKOPYRVWQ4V2SZ"

symbol = "IBM"

url = f"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={API_KEY}"

response = requests.get(url)

data = response.json()

print(data)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'IBM', '3. Last Refreshed': '2026-06-08', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2026-06-08': {'1. open': '286.4400', '2. high': '290.5000', '3. low': '279.4300', '4. close': '280.8200', '5. volume': '6790639'}, '2026-06-05': {'1. open': '300.0000', '2. high': '302.3000', '3. low': '281.0701', '4. close': '284.8400', '5. volume': '12509480'}, '2026-06-04': {'1. open': '307.4250', '2. high': '310.4400', '3. low': '300.1800', '4. close': '301.7700', '5. volume': '9608097'}, '2026-06-03': {'1. open': '318.2950', '2. high': '318.2950', '3. low': '302.5301', '4. close': '305.6300', '5. volume': '13926558'}, '2026-06-02': {'1. open': '313.7500', '2. high': '332.4600', '3. low': '310.1090', '4. close': '329.2300', '5. volume': '17210696'}, '2026-06-01': {'1. open': '322.5500', '2. high': '327.9800', '3. low': '308.0000', '4. close': '320.4200', '5. volume': '32880180'}, '2026-05-29': {'1. open': '277.3000', '2. high': '300.9999', '3. low': '273.3300', '4. close': '297.8000', '5. volume': '28480996'}, '2026-05-28': {'1. open': '261.0000', '2. high': '268.8900', '3. low': '257.0000', '4. close': '264.2200', '5. volume': '12432879'}, '2026-05-27': {'1. open': '250.4550', '2. high': '257.6200', '3. low': '250.4550', '4. close': '255.2000', '5. volume': '9275543'}, '2026-05-26': {'1. open': '254.5500', '2. high': '254.5500', '3. low': '245.4500', '4. close': '250.6900', '5. volume': '9256109'}, '2026-05-22': {'1. open': '262.0500', '2. high': '264.3800', '3. low': '253.3900', '4. close': '253.8400', '5. volume': '19072873'}, '2026-05-21': {'1. open': '232.5800', '2. high': '253.6300', '3. low': '230.9350', '4. close': '252.9700', '5. volume': '25707791'}, '2026-05-20': {'1. open': '221.0500', '2. high': '225.0000', '3. low': '216.7800', '4. close': '225.0000', '5. volume': '4858990'}, '2026-05-19': {'1. open': '224.5000', '2. high': '227.3500', '3. low': '221.9200', '4. close': '222.3300', '5. volume': '5937754'}, '2026-05-18': {'1. open': '218.5500', '2. high': '223.3300', '3. low': '217.7500', '4. close': '222.7500', '5. volume': '5946367'}, '2026-05-15': {'1. open': '218.2000', '2. high': '220.9100', '3. low': '217.6150', '4. close': '219.3000', '5. volume': '6154450'}, '2026-05-14': {'1. open': '215.5450', '2. high': '220.9600', '3. low': '215.0000', '4. close': '218.3700', '5. volume': '5906199'}, '2026-05-13': {'1. open': '218.2700', '2. high': '218.3100', '3. low': '212.3400', '4. close': '214.6400', '5. volume': '8361214'}, '2026-05-12': {'1. open': '224.4300', '2. high': '224.4300', '3. low': '219.2200', '4. close': '219.2200', '5. volume': '6045225'}, '2026-05-11': {'1. open': '228.6600', '2. high': '230.2300', '3. low': '222.5500', '4. close': '223.5500', '5. volume': '6677186'}, '2026-05-08': {'1. open': '229.7300', '2. high': '230.7050', '3. low': '224.8300', '4. close': '229.7600', '5. volume': '5332800'}, '2026-05-07': {'1. open': '227.5000', '2. high': '231.8200', '3. low': '227.4100', '4. close': '231.3100', '5. volume': '5485545'}, '2026-05-06': {'1. open': '228.7500', '2. high': '229.0000', '3. low': '224.3800', '4. close': '225.7400', '5. volume': '7673185'}, '2026-05-05': {'1. open': '230.1600', '2. high': '231.0000', '3. low': '227.1500', '4. close': '229.0300', '5. volume': '4221889'}, '2026-05-04': {'1. open': '232.0000', '2. high': '234.0900', '3. low': '228.6150', '4. close': '229.4800', '5. volume': '4003082'}, '2026-05-01': {'1. open': '234.5500', '2. high': '235.9500', '3. low': '231.7500', '4. close': '232.2000', '5. volume': '3582091'}, '2026-04-30': {'1. open': '226.5300', '2. high': '231.6000', '3. low': '224.9000', '4. close': '230.9800', '5. volume': '6283334'}, '2026-04-29': {'1. open': '230.3400', '2. high': '231.4800', '3. low': '226.8200', '4. close': '227.1000', '5. volume': '6443724'}, '2026-04-28': {'1. open': '230.5000', '2. high': '233.5550', '3. low': '228.4600', '4. close': '233.0400', '5. volume': '5162895'}, '2026-04-27': {'1. open': '229.9500', '2. high': '231.3200', '3. low': '227.1200', '4. close': '228.0500', '5. volume': '8060665'}, '2026-04-24': {'1. open': '231.9300', '2. high': '232.7999', '3. low': '225.0000', '4. close': '231.9800', '5. volume': '9816859'}, '2026-04-23': {'1. open': '232.2700', '2. high': '232.9100', '3. low': '221.7300', '4. close': '231.0800', '5. volume': '22297831'}, '2026-04-22': {'1. open': '254.5100', '2. high': '257.5400', '3. low': '247.2100', '4. close': '251.8600', '5. volume': '12190197'}, '2026-04-21': {'1. open': '254.0000', '2. high': '258.0900', '3. low': '251.8650', '4. close': '255.6800', '5. volume': '5584901'}, '2026-04-20': {'1. open': '255.0000', '2. high': '258.5000', '3. low': '252.5600', '4. close': '253.7100', '5. volume': '5157714'}, '2026-04-17': {'1. open': '254.6700', '2. high': '255.6500', '3. low': '251.0400', '4. close': '253.4700', '5. volume': '5671471'}, '2026-04-16': {'1. open': '248.7500', '2. high': '251.2200', '3. low': '246.1250', '4. close': '251.0000', '5. volume': '4817500'}, '2026-04-15': {'1. open': '242.2500', '2. high': '246.0600', '3. low': '240.9850', '4. close': '244.8000', '5. volume': '3879518'}, '2026-04-14': {'1. open': '238.7500', '2. high': '241.5375', '3. low': '238.1200', '4. close': '240.2700', '5. volume': '3777272'}, '2026-04-13': {'1. open': '233.6300', '2. high': '238.0700', '3. low': '231.7000', '4. close': '237.8200', '5. volume': '5349619'}, '2026-04-10': {'1. open': '239.1900', '2. high': '239.2674', '3. low': '230.5100', '4. close': '230.7600', '5. volume': '5869361'}, '2026-04-09': {'1. open': '240.8800', '2. high': '241.7400', '3. low': '233.7600', '4. close': '237.1800', '5. volume': '5078595'}, '2026-04-08': {'1. open': '248.6300', '2. high': '250.0000', '3. low': '240.8000', '4. close': '241.7400', '5. volume': '4771476'}, '2026-04-07': {'1. open': '245.3200', '2. high': '245.7600', '3. low': '241.1000', '4. close': '245.0700', '5. volume': '2356072'}, '2026-04-06': {'1. open': '248.1400', '2. high': '248.8999', '3. low': '244.7400', '4. close': '246.7400', '5. volume': '3376019'}, '2026-04-02': {'1. open': '243.0000', '2. high': '248.2103', '3. low': '241.4850', '4. close': '248.1600', '5. volume': '3350858'}, '2026-04-01': {'1. open': '242.1200', '2. high': '246.2618', '3. low': '240.1400', '4. close': '243.1400', '5. volume': '4228653'}, '2026-03-31': {'1. open': '240.2700', '2. high': '242.8500', '3. low': '236.3800', '4. close': '242.3900', '5. volume': '4750293'}, '2026-03-30': {'1. open': '237.8000', '2. high': '240.2100', '3. low': '236.1310', '4. close': '237.2500', '5. volume': '3882602'}, '2026-03-27': {'1. open': '238.8500', '2. high': '239.4400', '3. low': '233.7500', '4. close': '236.3400', '5. volume': '4853707'}, '2026-03-26': {'1. open': '240.5600', '2. high': '246.6742', '3. low': '239.8000', '4. close': '241.6700', '5. volume': '3606840'}, '2026-03-25': {'1. open': '243.6000', '2. high': '246.1900', '3. low': '238.0000', '4. close': '241.3900', '5. volume': '4207946'}, '2026-03-24': {'1. open': '246.4450', '2. high': '247.1100', '3. low': '238.0000', '4. close': '240.5900', '5. volume': '4151491'}, '2026-03-23': {'1. open': '246.5000', '2. high': '251.3500', '3. low': '244.7101', '4. close': '248.4400', '5. volume': '4972008'}, '2026-03-20': {'1. open': '249.0000', '2. high': '250.2800', '3. low': '241.7700', '4. close': '241.7700', '5. volume': '11314093'}, '2026-03-19': {'1. open': '249.4300', '2. high': '252.1900', '3. low': '248.2500', '4. close': '250.3700', '5. volume': '4249458'}, '2026-03-18': {'1. open': '254.1600', '2. high': '258.2800', '3. low': '250.1600', '4. close': '251.6000', '5. volume': '5177047'}, '2026-03-17': {'1. open': '250.5100', '2. high': '256.3900', '3. low': '250.0000', '4. close': '256.1100', '5. volume': '5840139'}, '2026-03-16': {'1. open': '247.8700', '2. high': '252.2000', '3. low': '246.1000', '4. close': '249.2500', '5. volume': '5674228'}, '2026-03-13': {'1. open': '247.6700', '2. high': '249.7200', '3. low': '244.7100', '4. close': '246.2800', '5. volume': '4338431'}, '2026-03-12': {'1. open': '247.1000', '2. high': '250.0450', '3. low': '245.6400', '4. close': '247.6800', '5. volume': '5547724'}, '2026-03-11': {'1. open': '250.0050', '2. high': '253.7150', '3. low': '247.2000', '4. close': '248.8700', '5. volume': '4012239'}, '2026-03-10': {'1. open': '253.2600', '2. high': '253.4400', '3. low': '246.5500', '4. close': '250.2000', '5. volume': '4937960'}, '2026-03-09': {'1. open': '255.3800', '2. high': '258.0800', '3. low': '251.5710', '4. close': '253.3300', '5. volume': '6126567'}, '2026-03-06': {'1. open': '256.4400', '2. high': '259.3999', '3. low': '252.2100', '4. close': '258.8500', '5. volume': '6234402'}, '2026-03-05': {'1. open': '249.3200', '2. high': '260.3800', '3. low': '249.0000', '4. close': '256.5500', '5. volume': '9899962'}, '2026-03-04': {'1. open': '245.7450', '2. high': '250.8500', '3. low': '244.9550', '4. close': '250.0600', '5. volume': '6084995'}, '2026-03-03': {'1. open': '236.3500', '2. high': '246.0900', '3. low': '234.2900', '4. close': '245.2800', '5. volume': '6960369'}, '2026-03-02': {'1. open': '235.7000', '2. high': '240.7800', '3. low': '233.7800', '4. close': '239.3700', '5. volume': '6220287'}, '2026-02-27': {'1. open': '238.0700', '2. high': '240.2100', '3. low': '234.5650', '4. close': '240.2100', '5. volume': '6642222'}, '2026-02-26': {'1. open': '239.7100', '2. high': '247.4899', '3. low': '238.9500', '4. close': '242.0100', '5. volume': '7343055'}, '2026-02-25': {'1. open': '233.2200', '2. high': '239.5500', '3. low': '231.2200', '4. close': '237.5400', '5. volume': '8569713'}, '2026-02-24': {'1. open': '227.8000', '2. high': '236.5937', '3. low': '223.6300', '4. close': '229.3200', '5. volume': '13379817'}, '2026-02-23': {'1. open': '254.3700', '2. high': '255.1900', '3. low': '220.7200', '4. close': '223.3500', '5. volume': '19522881'}, '2026-02-20': {'1. open': '255.1950', '2. high': '259.0400', '3. low': '253.8000', '4. close': '257.1600', '5. volume': '4708550'}, '2026-02-19': {'1. open': '256.0000', '2. high': '258.2800', '3. low': '253.5110', '4. close': '256.2800', '5. volume': '4948700'}, '2026-02-18': {'1. open': '258.6400', '2. high': '261.1100', '3. low': '256.2500', '4. close': '260.7900', '5. volume': '3949229'}, '2026-02-17': {'1. open': '259.2000', '2. high': '260.7000', '3. low': '254.6500', '4. close': '258.3100', '5. volume': '4929733'}, '2026-02-13': {'1. open': '260.0000', '2. high': '264.6600', '3. low': '256.6400', '4. close': '262.3800', '5. volume': '6842620'}, '2026-02-12': {'1. open': '270.3000', '2. high': '271.3000', '3. low': '257.2200', '4. close': '259.5200', '5. volume': '12565380'}, '2026-02-11': {'1. open': '292.3400', '2. high': '293.5000', '3. low': '272.3601', '4. close': '272.8100', '5. volume': '7628244'}, '2026-02-10': {'1. open': '294.9900', '2. high': '297.6100', '3. low': '290.3300', '4. close': '291.7600', '5. volume': '3837343'}, '2026-02-09': {'1. open': '295.9100', '2. high': '297.7200', '3. low': '291.4200', '4. close': '296.3400', '5. volume': '4627815'}, '2026-02-06': {'1. open': '292.5000', '2. high': '299.8900', '3. low': '290.6570', '4. close': '298.9300', '5. volume': '3744313'}, '2026-02-05': {'1. open': '286.1000', '2. high': '291.8100', '3. low': '285.1000', '4. close': '289.8900', '5. volume': '5532797'}, '2026-02-04': {'1. open': '291.4100', '2. high': '291.4100', '3. low': '278.9600', '4. close': '289.0500', '5. volume': '8708033'}, '2026-02-03': {'1. open': '312.4000', '2. high': '312.9750', '3. low': '283.8500', '4. close': '294.3100', '5. volume': '11296020'}, '2026-02-02': {'1. open': '307.5100', '2. high': '316.6400', '3. low': '306.4100', '4. close': '314.7300', '5. volume': '4581189'}, '2026-01-30': {'1. open': '307.6000', '2. high': '307.7830', '3. low': '299.7300', '4. close': '306.7000', '5. volume': '5940669'}, '2026-01-29': {'1. open': '317.8600', '2. high': '319.9000', '3. low': '303.4700', '4. close': '309.2400', '5. volume': '10124929'}, '2026-01-28': {'1. open': '294.1700', '2. high': '295.9500', '3. low': '291.2601', '4. close': '294.1600', '5. volume': '5790347'}, '2026-01-27': {'1. open': '297.1600', '2. high': '297.3300', '3. low': '293.2700', '4. close': '293.8600', '5. volume': '2944722'}, '2026-01-26': {'1. open': '293.1600', '2. high': '296.8150', '3. low': '293.1400', '4. close': '296.3300', '5. volume': '3726890'}, '2026-01-23': {'1. open': '294.0700', '2. high': '294.3350', '3. low': '289.7900', '4. close': '292.4400', '5. volume': '3298424'}, '2026-01-22': {'1. open': '299.4200', '2. high': '300.9300', '3. low': '293.5300', '4. close': '294.6700', '5. volume': '3670152'}, '2026-01-21': {'1. open': '292.7600', '2. high': '297.6700', '3. low': '292.5100', '4. close': '297.5400', '5. volume': '5185023'}, '2026-01-20': {'1. open': '301.3500', '2. high': '301.6000', '3. low': '290.1600', '4. close': '291.3500', '5. volume': '7211706'}, '2026-01-16': {'1. open': '301.0000', '2. high': '307.4500', '3. low': '300.7800', '4. close': '305.6700', '5. volume': '6199635'}, '2026-01-15': {'1. open': '309.0000', '2. high': '311.8800', '3. low': '297.0400', '4. close': '297.9500', '5. volume': '4932480'}, '2026-01-14': {'1. open': '303.5000', '2. high': '309.1900', '3. low': '301.5000', '4. close': '309.0300', '5. volume': '3779045'}}}

In [214]:
time_series = data["Time Series (Daily)"]

df = pd.DataFrame(time_series).T

print(df.head())

             1. open   2. high    3. low  4. close 5. volume
2026-06-08  286.4400  290.5000  279.4300  280.8200   6790639
2026-06-05  300.0000  302.3000  281.0701  284.8400  12509480
2026-06-04  307.4250  310.4400  300.1800  301.7700   9608097
2026-06-03  318.2950  318.2950  302.5301  305.6300  13926558
2026-06-02  313.7500  332.4600  310.1090  329.2300  17210696

In [215]:
df

             1. open   2. high    3. low  4. close 5. volume
2026-06-08  286.4400  290.5000  279.4300  280.8200   6790639
2026-06-05  300.0000  302.3000  281.0701  284.8400  12509480
2026-06-04  307.4250  310.4400  300.1800  301.7700   9608097
2026-06-03  318.2950  318.2950  302.5301  305.6300  13926558
2026-06-02  313.7500  332.4600  310.1090  329.2300  17210696
...              ...       ...       ...       ...       ...
2026-01-21  292.7600  297.6700  292.5100  297.5400   5185023
2026-01-20  301.3500  301.6000  290.1600  291.3500   7211706
2026-01-16  301.0000  307.4500  300.7800  305.6700   6199635
2026-01-15  309.0000  311.8800  297.0400  297.9500   4932480
2026-01-14  303.5000  309.1900  301.5000  309.0300   3779045

[100 rows x 5 columns]

In [216]:
df.dtypes

1. open      str
2. high      str
3. low       str
4. close     str
5. volume    str
dtype: object

In [217]:
df = df.astype(float)

print(df.dtypes)

1. open      float64
2. high      float64
3. low       float64
4. close     float64
5. volume    float64
dtype: object

In [218]:
df.index = pd.to_datetime(df.index)

In [219]:
df = df.sort_index()

In [220]:
df

            1. open  2. high    3. low  4. close   5. volume
2026-01-14  303.500  309.190  301.5000    309.03   3779045.0
2026-01-15  309.000  311.880  297.0400    297.95   4932480.0
2026-01-16  301.000  307.450  300.7800    305.67   6199635.0
2026-01-20  301.350  301.600  290.1600    291.35   7211706.0
2026-01-21  292.760  297.670  292.5100    297.54   5185023.0
...             ...      ...       ...       ...         ...
2026-06-02  313.750  332.460  310.1090    329.23  17210696.0
2026-06-03  318.295  318.295  302.5301    305.63  13926558.0
2026-06-04  307.425  310.440  300.1800    301.77   9608097.0
2026-06-05  300.000  302.300  281.0701    284.84  12509480.0
2026-06-08  286.440  290.500  279.4300    280.82   6790639.0

[100 rows x 5 columns]

In [221]:
df.columns = ["Open", "High", "Low", "Close", "Volume"]

In [222]:
df["Target"] = df["Close"].shift(-1)

In [223]:
df

               Open     High       Low   Close      Volume  Target
2026-01-14  303.500  309.190  301.5000  309.03   3779045.0  297.95
2026-01-15  309.000  311.880  297.0400  297.95   4932480.0  305.67
2026-01-16  301.000  307.450  300.7800  305.67   6199635.0  291.35
2026-01-20  301.350  301.600  290.1600  291.35   7211706.0  297.54
2026-01-21  292.760  297.670  292.5100  297.54   5185023.0  294.67
...             ...      ...       ...     ...         ...     ...
2026-06-02  313.750  332.460  310.1090  329.23  17210696.0  305.63
2026-06-03  318.295  318.295  302.5301  305.63  13926558.0  301.77
2026-06-04  307.425  310.440  300.1800  301.77   9608097.0  284.84
2026-06-05  300.000  302.300  281.0701  284.84  12509480.0  280.82
2026-06-08  286.440  290.500  279.4300  280.82   6790639.0     NaN

[100 rows x 6 columns]

In [224]:
df.isnull().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
Target    1
dtype: int64

In [225]:
df.dropna(inplace=True)

In [226]:
df.isnull().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
Target    0
dtype: int64

In [227]:
x=df.drop("Target",axis=1)
y=df["Target"]

print(x.head())
print(y.head())

              Open    High     Low   Close     Volume
2026-01-14  303.50  309.19  301.50  309.03  3779045.0
2026-01-15  309.00  311.88  297.04  297.95  4932480.0
2026-01-16  301.00  307.45  300.78  305.67  6199635.0
2026-01-20  301.35  301.60  290.16  291.35  7211706.0
2026-01-21  292.76  297.67  292.51  297.54  5185023.0
2026-01-14    297.95
2026-01-15    305.67
2026-01-16    291.35
2026-01-20    297.54
2026-01-21    294.67
Name: Target, dtype: float64

In [228]:
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,shuffle=False
)

In [229]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

In [230]:
model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)

In [231]:
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [232]:
y_pred = model.predict(x_test)

In [233]:
mae = mean_absolute_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)

print("R2 Score:", r2)

Mean Absolute Error: 15.540059722900395
R2 Score: 0.7006092544753686

In [234]:
result = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

print(result.head())

            Actual   Predicted
2026-05-08  223.55  230.915955
2026-05-11  219.22  231.760834
2026-05-12  214.64  232.239990
2026-05-13  218.37  232.401108
2026-05-14  219.30  232.239990