In [11]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv("Bangalore.csv")
df

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
0,30000000,3340,JP Nagar Phase 1,4,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
1,7888000,1045,Dasarahalli on Tumkur Road,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,4866000,1179,Kannur on Thanisandra Main Road,2,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
3,8358000,1675,Doddanekundi,3,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,6845000,1670,Kengeri,3,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6202,5364000,590,Chandapura,1,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6203,8716000,1179,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6204,7373000,1143,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6205,4985000,1680,Kasavanahalli,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6206,10900000,1162,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9

In [13]:
print("\n",df.head()) 
print("\n",df.shape) 
print("\n",df.info()) 
print("\n",df.describe())

       Price  Area                         Location  No. of Bedrooms  Resale  \
0  30000000  3340                 JP Nagar Phase 1                4       0
1   7888000  1045       Dasarahalli on Tumkur Road                2       0
2   4866000  1179  Kannur on Thanisandra Main Road                2       0
3   8358000  1675                     Doddanekundi                3       0
4   6845000  1670                          Kengeri                3       0

   MaintenanceStaff  Gymnasium  SwimmingPool  LandscapedGardens  JoggingTrack  \
0                 1          1             1                  1             1
1                 0          1             1                  1             1
2                 0          1             1                  1             1
3                 0          0             0                  0             0
4                 1          1             1                  1             1

   ...  LiftAvailable  BED  VaastuCompliant  Microwave  GolfCourse  TV  \
0  ...              1    0                0          0           0   0
1  ...              1    0                1          0           0   0
2  ...              1    0                0          0           0   0
3  ...              1    0                0          0           0   0
4  ...              1    0                0          0           0   0

   DiningTable  Sofa  Wardrobe  Stadium
0            0     0         0        0
1            0     0         0        0
2            0     0         0        0
3            0     0         0        0
4            0     0         0        0

[5 rows x 40 columns]

 (6207, 40)
<class 'pandas.DataFrame'>
RangeIndex: 6207 entries, 0 to 6206
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Price                6207 non-null   int64
 1   Area                 6207 non-null   int64
 2   Location             6207 non-null   str
 3   No. of Bedrooms      6207 non-null   int64
 4   Resale               6207 non-null   int64
 5   MaintenanceStaff     6207 non-null   int64
 6   Gymnasium            6207 non-null   int64
 7   SwimmingPool         6207 non-null   int64
 8   LandscapedGardens    6207 non-null   int64
 9   JoggingTrack         6207 non-null   int64
 10  RainWaterHarvesting  6207 non-null   int64
 11  IndoorGames          6207 non-null   int64
 12  ShoppingMall         6207 non-null   int64
 13  Intercom             6207 non-null   int64
 14  SportsFacility       6207 non-null   int64
 15  ATM                  6207 non-null   int64
 16  ClubHouse            6207 non-null   int64
 17  School               6207 non-null   int64
 18  24X7Security         6207 non-null   int64
 19  PowerBackup          6207 non-null   int64
 20  CarParking           6207 non-null   int64
 21  StaffQuarter         6207 non-null   int64
 22  Cafeteria            6207 non-null   int64
 23  MultipurposeRoom     6207 non-null   int64
 24  Hospital             6207 non-null   int64
 25  WashingMachine       6207 non-null   int64
 26  Gasconnection        6207 non-null   int64
 27  AC                   6207 non-null   int64
 28  Wifi                 6207 non-null   int64
 29  Children'splayarea   6207 non-null   int64
 30  LiftAvailable        6207 non-null   int64
 31  BED                  6207 non-null   int64
 32  VaastuCompliant      6207 non-null   int64
 33  Microwave            6207 non-null   int64
 34  GolfCourse           6207 non-null   int64
 35  TV                   6207 non-null   int64
 36  DiningTable          6207 non-null   int64
 37  Sofa                 6207 non-null   int64
 38  Wardrobe             6207 non-null   int64
 39  Stadium              6207 non-null   int64
dtypes: int64(39), str(1)
memory usage: 1.9 MB

 None

               Price         Area  No. of Bedrooms       Resale  \
count  6.207000e+03  6207.000000      6207.000000  6207.000000
mean   1.058510e+07  1526.094248         2.556952     0.078782
std    1.410943e+07   764.845609         0.694300     0.269420
min    2.000000e+06   415.000000         1.000000     0.000000
25%    5.000000e+06  1110.000000         2.000000     0.000000
50%    7.368000e+06  1340.000000         3.000000     0.000000
75%    1.070000e+07  1662.500000         3.000000     0.000000
max    3.000000e+08  9900.000000         7.000000     1.000000

       MaintenanceStaff    Gymnasium  SwimmingPool  LandscapedGardens  \
count       6207.000000  6207.000000   6207.000000        6207.000000
mean           6.208797     6.461576      6.436121           6.382471
std            4.126883     3.752421      3.792567           3.875271
min            0.000000     0.000000      0.000000           0.000000
25%            0.000000     1.000000      1.000000           1.000000
50%            9.000000     9.000000      9.000000           9.000000
75%            9.000000     9.000000      9.000000           9.000000
max            9.000000     9.000000      9.000000           9.000000

       JoggingTrack  RainWaterHarvesting  ...  LiftAvailable          BED  \
count   6207.000000          6207.000000  ...    6207.000000  6207.000000
mean       6.396649             6.373933  ...       6.438537     6.211052
std        3.853661             3.888204  ...       3.788782     4.123761
min        0.000000             0.000000  ...       0.000000     0.000000
25%        1.000000             1.000000  ...       1.000000     0.000000
50%        9.000000             9.000000  ...       9.000000     9.000000
75%        9.000000             9.000000  ...       9.000000     9.000000
max        9.000000             9.000000  ...       9.000000     9.000000

       VaastuCompliant    Microwave   GolfCourse           TV  DiningTable  \
count      6207.000000  6207.000000  6207.000000  6207.000000  6207.000000
mean          6.311100     6.210569     6.181569     6.210569     6.210569
std           3.981513     4.124430     4.164294     4.124430     4.124430
min           0.000000     0.000000     0.000000     0.000000     0.000000
25%           1.000000     0.000000     0.000000     0.000000     0.000000
50%           9.000000     9.000000     9.000000     9.000000     9.000000
75%           9.000000     9.000000     9.000000     9.000000     9.000000
max           9.000000     9.000000     9.000000     9.000000     9.000000

              Sofa     Wardrobe      Stadium
count  6207.000000  6207.000000  6207.000000
mean      6.210569     6.171097     6.210569
std       4.124430     4.178546     4.124430
min       0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000
50%       9.000000     9.000000     9.000000
75%       9.000000     9.000000     9.000000
max       9.000000     9.000000     9.000000

[8 rows x 39 columns]

In [14]:
df.duplicated().sum()

np.int64(686)

In [15]:
df = df.drop_duplicates()
df

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
0,30000000,3340,JP Nagar Phase 1,4,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
1,7888000,1045,Dasarahalli on Tumkur Road,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,4866000,1179,Kannur on Thanisandra Main Road,2,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
3,8358000,1675,Doddanekundi,3,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,6845000,1670,Kengeri,3,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6202,5364000,590,Chandapura,1,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6203,8716000,1179,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6204,7373000,1143,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6205,4985000,1680,Kasavanahalli,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6206,10900000,1162,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9

In [16]:
df.columns

Index(['Price', 'Area', 'Location', 'No. of Bedrooms', 'Resale',
       'MaintenanceStaff', 'Gymnasium', 'SwimmingPool', 'LandscapedGardens',
       'JoggingTrack', 'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall',
       'Intercom', 'SportsFacility', 'ATM', 'ClubHouse', 'School',
       '24X7Security', 'PowerBackup', 'CarParking', 'StaffQuarter',
       'Cafeteria', 'MultipurposeRoom', 'Hospital', 'WashingMachine',
       'Gasconnection', 'AC', 'Wifi', 'Children'splayarea', 'LiftAvailable',
       'BED', 'VaastuCompliant', 'Microwave', 'GolfCourse', 'TV',
       'DiningTable', 'Sofa', 'Wardrobe', 'Stadium'],
      dtype='str')

In [17]:
numeric_columns = df.select_dtypes(include=np.number).columns

print(numeric_columns)


for col in numeric_columns:

    q1 = df[col].quantile(0.25)

    q3 = df[col].quantile(0.75)

    iqr = q3 - q1

    lower = q1 - 1.5 * iqr

    upper = q3 + 1.5 * iqr

    df = df[
        (df[col] >= lower) &
        (df[col] <= upper)
    ]


if 'Price' in df.columns:
    df = df[df['Price'] > 0]

if 'Area' in df.columns:
    df = df[df['Area'] > 0]

print(df.shape)

Index(['Price', 'Area', 'No. of Bedrooms', 'Resale', 'MaintenanceStaff',
       'Gymnasium', 'SwimmingPool', 'LandscapedGardens', 'JoggingTrack',
       'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall', 'Intercom',
       'SportsFacility', 'ATM', 'ClubHouse', 'School', '24X7Security',
       'PowerBackup', 'CarParking', 'StaffQuarter', 'Cafeteria',
       'MultipurposeRoom', 'Hospital', 'WashingMachine', 'Gasconnection', 'AC',
       'Wifi', 'Children'splayarea', 'LiftAvailable', 'BED', 'VaastuCompliant',
       'Microwave', 'GolfCourse', 'TV', 'DiningTable', 'Sofa', 'Wardrobe',
       'Stadium'],
      dtype='str')
(4297, 40)

In [18]:
df.to_csv("clean_Bangalore.csv", index=False)